<?php
/**
 * Template1
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocSpring
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DocSpring\Model;

use \ArrayAccess;
use \DocSpring\ObjectSerializer;

/**
 * Template1 Class Doc Comment
 *
 * @category Class
 * @package  DocSpring
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Template1 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'template_1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'document_processed' => 'bool',
        'expiration_interval' => 'string',
        'scss' => 'string',
        'document_state' => 'string',
        'expire_after' => 'float',
        'description' => 'string',
        'slack_webhook_url' => 'string',
        'demo' => 'bool',
        'path' => 'string',
        'header_html' => 'string',
        'public_web_form' => 'bool',
        'field_order' => 'float[][]',
        'permanent_document_url' => 'string',
        'html' => 'string',
        'template_type' => 'string',
        'id' => 'string',
        'page_dimensions' => 'float[][]',
        'locked' => 'bool',
        'page_count' => 'float',
        'encrypt_pdfs' => 'bool',
        'webhook_url' => 'string',
        'embed_domains' => 'string[]',
        'parent_folder_id' => 'string',
        'allow_additional_properties' => 'bool',
        'encrypt_pdfs_password' => 'string',
        'public_submissions' => 'bool',
        'shared_field_data' => 'object',
        'document_md5' => 'string',
        'first_template' => 'bool',
        'defaults' => '\DocSpring\Model\Template1Defaults',
        'editable_submissions' => 'bool',
        'expire_submissions' => 'bool',
        'name' => 'string',
        'footer_html' => 'string',
        'document_parse_error' => 'bool',
        'fields' => 'object',
        'document_filename' => 'string',
        'redirect_url' => 'string',
        'document_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'document_processed' => null,
        'expiration_interval' => null,
        'scss' => null,
        'document_state' => null,
        'expire_after' => null,
        'description' => null,
        'slack_webhook_url' => null,
        'demo' => null,
        'path' => null,
        'header_html' => null,
        'public_web_form' => null,
        'field_order' => null,
        'permanent_document_url' => null,
        'html' => null,
        'template_type' => null,
        'id' => null,
        'page_dimensions' => null,
        'locked' => null,
        'page_count' => null,
        'encrypt_pdfs' => null,
        'webhook_url' => null,
        'embed_domains' => null,
        'parent_folder_id' => null,
        'allow_additional_properties' => null,
        'encrypt_pdfs_password' => null,
        'public_submissions' => null,
        'shared_field_data' => null,
        'document_md5' => null,
        'first_template' => null,
        'defaults' => null,
        'editable_submissions' => null,
        'expire_submissions' => null,
        'name' => null,
        'footer_html' => null,
        'document_parse_error' => null,
        'fields' => null,
        'document_filename' => null,
        'redirect_url' => null,
        'document_url' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'document_processed' => 'document_processed',
        'expiration_interval' => 'expiration_interval',
        'scss' => 'scss',
        'document_state' => 'document_state',
        'expire_after' => 'expire_after',
        'description' => 'description',
        'slack_webhook_url' => 'slack_webhook_url',
        'demo' => 'demo',
        'path' => 'path',
        'header_html' => 'header_html',
        'public_web_form' => 'public_web_form',
        'field_order' => 'field_order',
        'permanent_document_url' => 'permanent_document_url',
        'html' => 'html',
        'template_type' => 'template_type',
        'id' => 'id',
        'page_dimensions' => 'page_dimensions',
        'locked' => 'locked',
        'page_count' => 'page_count',
        'encrypt_pdfs' => 'encrypt_pdfs',
        'webhook_url' => 'webhook_url',
        'embed_domains' => 'embed_domains',
        'parent_folder_id' => 'parent_folder_id',
        'allow_additional_properties' => 'allow_additional_properties',
        'encrypt_pdfs_password' => 'encrypt_pdfs_password',
        'public_submissions' => 'public_submissions',
        'shared_field_data' => 'shared_field_data',
        'document_md5' => 'document_md5',
        'first_template' => 'first_template',
        'defaults' => 'defaults',
        'editable_submissions' => 'editable_submissions',
        'expire_submissions' => 'expire_submissions',
        'name' => 'name',
        'footer_html' => 'footer_html',
        'document_parse_error' => 'document_parse_error',
        'fields' => 'fields',
        'document_filename' => 'document_filename',
        'redirect_url' => 'redirect_url',
        'document_url' => 'document_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'document_processed' => 'setDocumentProcessed',
        'expiration_interval' => 'setExpirationInterval',
        'scss' => 'setScss',
        'document_state' => 'setDocumentState',
        'expire_after' => 'setExpireAfter',
        'description' => 'setDescription',
        'slack_webhook_url' => 'setSlackWebhookUrl',
        'demo' => 'setDemo',
        'path' => 'setPath',
        'header_html' => 'setHeaderHtml',
        'public_web_form' => 'setPublicWebForm',
        'field_order' => 'setFieldOrder',
        'permanent_document_url' => 'setPermanentDocumentUrl',
        'html' => 'setHtml',
        'template_type' => 'setTemplateType',
        'id' => 'setId',
        'page_dimensions' => 'setPageDimensions',
        'locked' => 'setLocked',
        'page_count' => 'setPageCount',
        'encrypt_pdfs' => 'setEncryptPdfs',
        'webhook_url' => 'setWebhookUrl',
        'embed_domains' => 'setEmbedDomains',
        'parent_folder_id' => 'setParentFolderId',
        'allow_additional_properties' => 'setAllowAdditionalProperties',
        'encrypt_pdfs_password' => 'setEncryptPdfsPassword',
        'public_submissions' => 'setPublicSubmissions',
        'shared_field_data' => 'setSharedFieldData',
        'document_md5' => 'setDocumentMd5',
        'first_template' => 'setFirstTemplate',
        'defaults' => 'setDefaults',
        'editable_submissions' => 'setEditableSubmissions',
        'expire_submissions' => 'setExpireSubmissions',
        'name' => 'setName',
        'footer_html' => 'setFooterHtml',
        'document_parse_error' => 'setDocumentParseError',
        'fields' => 'setFields',
        'document_filename' => 'setDocumentFilename',
        'redirect_url' => 'setRedirectUrl',
        'document_url' => 'setDocumentUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'document_processed' => 'getDocumentProcessed',
        'expiration_interval' => 'getExpirationInterval',
        'scss' => 'getScss',
        'document_state' => 'getDocumentState',
        'expire_after' => 'getExpireAfter',
        'description' => 'getDescription',
        'slack_webhook_url' => 'getSlackWebhookUrl',
        'demo' => 'getDemo',
        'path' => 'getPath',
        'header_html' => 'getHeaderHtml',
        'public_web_form' => 'getPublicWebForm',
        'field_order' => 'getFieldOrder',
        'permanent_document_url' => 'getPermanentDocumentUrl',
        'html' => 'getHtml',
        'template_type' => 'getTemplateType',
        'id' => 'getId',
        'page_dimensions' => 'getPageDimensions',
        'locked' => 'getLocked',
        'page_count' => 'getPageCount',
        'encrypt_pdfs' => 'getEncryptPdfs',
        'webhook_url' => 'getWebhookUrl',
        'embed_domains' => 'getEmbedDomains',
        'parent_folder_id' => 'getParentFolderId',
        'allow_additional_properties' => 'getAllowAdditionalProperties',
        'encrypt_pdfs_password' => 'getEncryptPdfsPassword',
        'public_submissions' => 'getPublicSubmissions',
        'shared_field_data' => 'getSharedFieldData',
        'document_md5' => 'getDocumentMd5',
        'first_template' => 'getFirstTemplate',
        'defaults' => 'getDefaults',
        'editable_submissions' => 'getEditableSubmissions',
        'expire_submissions' => 'getExpireSubmissions',
        'name' => 'getName',
        'footer_html' => 'getFooterHtml',
        'document_parse_error' => 'getDocumentParseError',
        'fields' => 'getFields',
        'document_filename' => 'getDocumentFilename',
        'redirect_url' => 'getRedirectUrl',
        'document_url' => 'getDocumentUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const EXPIRATION_INTERVAL_MINUTES = 'minutes';
    const EXPIRATION_INTERVAL_HOURS = 'hours';
    const EXPIRATION_INTERVAL_DAYS = 'days';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getExpirationIntervalAllowableValues()
    {
        return [
            self::EXPIRATION_INTERVAL_MINUTES,
            self::EXPIRATION_INTERVAL_HOURS,
            self::EXPIRATION_INTERVAL_DAYS,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['document_processed'] = isset($data['document_processed']) ? $data['document_processed'] : null;
        $this->container['expiration_interval'] = isset($data['expiration_interval']) ? $data['expiration_interval'] : null;
        $this->container['scss'] = isset($data['scss']) ? $data['scss'] : null;
        $this->container['document_state'] = isset($data['document_state']) ? $data['document_state'] : null;
        $this->container['expire_after'] = isset($data['expire_after']) ? $data['expire_after'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['slack_webhook_url'] = isset($data['slack_webhook_url']) ? $data['slack_webhook_url'] : null;
        $this->container['demo'] = isset($data['demo']) ? $data['demo'] : null;
        $this->container['path'] = isset($data['path']) ? $data['path'] : null;
        $this->container['header_html'] = isset($data['header_html']) ? $data['header_html'] : null;
        $this->container['public_web_form'] = isset($data['public_web_form']) ? $data['public_web_form'] : null;
        $this->container['field_order'] = isset($data['field_order']) ? $data['field_order'] : null;
        $this->container['permanent_document_url'] = isset($data['permanent_document_url']) ? $data['permanent_document_url'] : null;
        $this->container['html'] = isset($data['html']) ? $data['html'] : null;
        $this->container['template_type'] = isset($data['template_type']) ? $data['template_type'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['page_dimensions'] = isset($data['page_dimensions']) ? $data['page_dimensions'] : null;
        $this->container['locked'] = isset($data['locked']) ? $data['locked'] : null;
        $this->container['page_count'] = isset($data['page_count']) ? $data['page_count'] : null;
        $this->container['encrypt_pdfs'] = isset($data['encrypt_pdfs']) ? $data['encrypt_pdfs'] : null;
        $this->container['webhook_url'] = isset($data['webhook_url']) ? $data['webhook_url'] : null;
        $this->container['embed_domains'] = isset($data['embed_domains']) ? $data['embed_domains'] : null;
        $this->container['parent_folder_id'] = isset($data['parent_folder_id']) ? $data['parent_folder_id'] : null;
        $this->container['allow_additional_properties'] = isset($data['allow_additional_properties']) ? $data['allow_additional_properties'] : null;
        $this->container['encrypt_pdfs_password'] = isset($data['encrypt_pdfs_password']) ? $data['encrypt_pdfs_password'] : null;
        $this->container['public_submissions'] = isset($data['public_submissions']) ? $data['public_submissions'] : null;
        $this->container['shared_field_data'] = isset($data['shared_field_data']) ? $data['shared_field_data'] : null;
        $this->container['document_md5'] = isset($data['document_md5']) ? $data['document_md5'] : null;
        $this->container['first_template'] = isset($data['first_template']) ? $data['first_template'] : null;
        $this->container['defaults'] = isset($data['defaults']) ? $data['defaults'] : null;
        $this->container['editable_submissions'] = isset($data['editable_submissions']) ? $data['editable_submissions'] : null;
        $this->container['expire_submissions'] = isset($data['expire_submissions']) ? $data['expire_submissions'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['footer_html'] = isset($data['footer_html']) ? $data['footer_html'] : null;
        $this->container['document_parse_error'] = isset($data['document_parse_error']) ? $data['document_parse_error'] : null;
        $this->container['fields'] = isset($data['fields']) ? $data['fields'] : null;
        $this->container['document_filename'] = isset($data['document_filename']) ? $data['document_filename'] : null;
        $this->container['redirect_url'] = isset($data['redirect_url']) ? $data['redirect_url'] : null;
        $this->container['document_url'] = isset($data['document_url']) ? $data['document_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getExpirationIntervalAllowableValues();
        if (!is_null($this->container['expiration_interval']) && !in_array($this->container['expiration_interval'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'expiration_interval', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets document_processed
     *
     * @return bool|null
     */
    public function getDocumentProcessed()
    {
        return $this->container['document_processed'];
    }

    /**
     * Sets document_processed
     *
     * @param bool|null $document_processed document_processed
     *
     * @return $this
     */
    public function setDocumentProcessed($document_processed)
    {
        $this->container['document_processed'] = $document_processed;

        return $this;
    }

    /**
     * Gets expiration_interval
     *
     * @return string|null
     */
    public function getExpirationInterval()
    {
        return $this->container['expiration_interval'];
    }

    /**
     * Sets expiration_interval
     *
     * @param string|null $expiration_interval expiration_interval
     *
     * @return $this
     */
    public function setExpirationInterval($expiration_interval)
    {
        $allowedValues = $this->getExpirationIntervalAllowableValues();
        if (!is_null($expiration_interval) && !in_array($expiration_interval, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'expiration_interval', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['expiration_interval'] = $expiration_interval;

        return $this;
    }

    /**
     * Gets scss
     *
     * @return string|null
     */
    public function getScss()
    {
        return $this->container['scss'];
    }

    /**
     * Sets scss
     *
     * @param string|null $scss scss
     *
     * @return $this
     */
    public function setScss($scss)
    {
        $this->container['scss'] = $scss;

        return $this;
    }

    /**
     * Gets document_state
     *
     * @return string|null
     */
    public function getDocumentState()
    {
        return $this->container['document_state'];
    }

    /**
     * Sets document_state
     *
     * @param string|null $document_state document_state
     *
     * @return $this
     */
    public function setDocumentState($document_state)
    {
        $this->container['document_state'] = $document_state;

        return $this;
    }

    /**
     * Gets expire_after
     *
     * @return float|null
     */
    public function getExpireAfter()
    {
        return $this->container['expire_after'];
    }

    /**
     * Sets expire_after
     *
     * @param float|null $expire_after expire_after
     *
     * @return $this
     */
    public function setExpireAfter($expire_after)
    {
        $this->container['expire_after'] = $expire_after;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets slack_webhook_url
     *
     * @return string|null
     */
    public function getSlackWebhookUrl()
    {
        return $this->container['slack_webhook_url'];
    }

    /**
     * Sets slack_webhook_url
     *
     * @param string|null $slack_webhook_url slack_webhook_url
     *
     * @return $this
     */
    public function setSlackWebhookUrl($slack_webhook_url)
    {
        $this->container['slack_webhook_url'] = $slack_webhook_url;

        return $this;
    }

    /**
     * Gets demo
     *
     * @return bool|null
     */
    public function getDemo()
    {
        return $this->container['demo'];
    }

    /**
     * Sets demo
     *
     * @param bool|null $demo demo
     *
     * @return $this
     */
    public function setDemo($demo)
    {
        $this->container['demo'] = $demo;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path path
     *
     * @return $this
     */
    public function setPath($path)
    {
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets header_html
     *
     * @return string|null
     */
    public function getHeaderHtml()
    {
        return $this->container['header_html'];
    }

    /**
     * Sets header_html
     *
     * @param string|null $header_html header_html
     *
     * @return $this
     */
    public function setHeaderHtml($header_html)
    {
        $this->container['header_html'] = $header_html;

        return $this;
    }

    /**
     * Gets public_web_form
     *
     * @return bool|null
     */
    public function getPublicWebForm()
    {
        return $this->container['public_web_form'];
    }

    /**
     * Sets public_web_form
     *
     * @param bool|null $public_web_form public_web_form
     *
     * @return $this
     */
    public function setPublicWebForm($public_web_form)
    {
        $this->container['public_web_form'] = $public_web_form;

        return $this;
    }

    /**
     * Gets field_order
     *
     * @return float[][]|null
     */
    public function getFieldOrder()
    {
        return $this->container['field_order'];
    }

    /**
     * Sets field_order
     *
     * @param float[][]|null $field_order field_order
     *
     * @return $this
     */
    public function setFieldOrder($field_order)
    {
        $this->container['field_order'] = $field_order;

        return $this;
    }

    /**
     * Gets permanent_document_url
     *
     * @return string|null
     */
    public function getPermanentDocumentUrl()
    {
        return $this->container['permanent_document_url'];
    }

    /**
     * Sets permanent_document_url
     *
     * @param string|null $permanent_document_url permanent_document_url
     *
     * @return $this
     */
    public function setPermanentDocumentUrl($permanent_document_url)
    {
        $this->container['permanent_document_url'] = $permanent_document_url;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html html
     *
     * @return $this
     */
    public function setHtml($html)
    {
        $this->container['html'] = $html;

        return $this;
    }

    /**
     * Gets template_type
     *
     * @return string|null
     */
    public function getTemplateType()
    {
        return $this->container['template_type'];
    }

    /**
     * Sets template_type
     *
     * @param string|null $template_type template_type
     *
     * @return $this
     */
    public function setTemplateType($template_type)
    {
        $this->container['template_type'] = $template_type;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets page_dimensions
     *
     * @return float[][]|null
     */
    public function getPageDimensions()
    {
        return $this->container['page_dimensions'];
    }

    /**
     * Sets page_dimensions
     *
     * @param float[][]|null $page_dimensions page_dimensions
     *
     * @return $this
     */
    public function setPageDimensions($page_dimensions)
    {
        $this->container['page_dimensions'] = $page_dimensions;

        return $this;
    }

    /**
     * Gets locked
     *
     * @return bool|null
     */
    public function getLocked()
    {
        return $this->container['locked'];
    }

    /**
     * Sets locked
     *
     * @param bool|null $locked locked
     *
     * @return $this
     */
    public function setLocked($locked)
    {
        $this->container['locked'] = $locked;

        return $this;
    }

    /**
     * Gets page_count
     *
     * @return float|null
     */
    public function getPageCount()
    {
        return $this->container['page_count'];
    }

    /**
     * Sets page_count
     *
     * @param float|null $page_count page_count
     *
     * @return $this
     */
    public function setPageCount($page_count)
    {
        $this->container['page_count'] = $page_count;

        return $this;
    }

    /**
     * Gets encrypt_pdfs
     *
     * @return bool|null
     */
    public function getEncryptPdfs()
    {
        return $this->container['encrypt_pdfs'];
    }

    /**
     * Sets encrypt_pdfs
     *
     * @param bool|null $encrypt_pdfs encrypt_pdfs
     *
     * @return $this
     */
    public function setEncryptPdfs($encrypt_pdfs)
    {
        $this->container['encrypt_pdfs'] = $encrypt_pdfs;

        return $this;
    }

    /**
     * Gets webhook_url
     *
     * @return string|null
     */
    public function getWebhookUrl()
    {
        return $this->container['webhook_url'];
    }

    /**
     * Sets webhook_url
     *
     * @param string|null $webhook_url webhook_url
     *
     * @return $this
     */
    public function setWebhookUrl($webhook_url)
    {
        $this->container['webhook_url'] = $webhook_url;

        return $this;
    }

    /**
     * Gets embed_domains
     *
     * @return string[]|null
     */
    public function getEmbedDomains()
    {
        return $this->container['embed_domains'];
    }

    /**
     * Sets embed_domains
     *
     * @param string[]|null $embed_domains embed_domains
     *
     * @return $this
     */
    public function setEmbedDomains($embed_domains)
    {
        $this->container['embed_domains'] = $embed_domains;

        return $this;
    }

    /**
     * Gets parent_folder_id
     *
     * @return string|null
     */
    public function getParentFolderId()
    {
        return $this->container['parent_folder_id'];
    }

    /**
     * Sets parent_folder_id
     *
     * @param string|null $parent_folder_id parent_folder_id
     *
     * @return $this
     */
    public function setParentFolderId($parent_folder_id)
    {
        $this->container['parent_folder_id'] = $parent_folder_id;

        return $this;
    }

    /**
     * Gets allow_additional_properties
     *
     * @return bool|null
     */
    public function getAllowAdditionalProperties()
    {
        return $this->container['allow_additional_properties'];
    }

    /**
     * Sets allow_additional_properties
     *
     * @param bool|null $allow_additional_properties allow_additional_properties
     *
     * @return $this
     */
    public function setAllowAdditionalProperties($allow_additional_properties)
    {
        $this->container['allow_additional_properties'] = $allow_additional_properties;

        return $this;
    }

    /**
     * Gets encrypt_pdfs_password
     *
     * @return string|null
     */
    public function getEncryptPdfsPassword()
    {
        return $this->container['encrypt_pdfs_password'];
    }

    /**
     * Sets encrypt_pdfs_password
     *
     * @param string|null $encrypt_pdfs_password encrypt_pdfs_password
     *
     * @return $this
     */
    public function setEncryptPdfsPassword($encrypt_pdfs_password)
    {
        $this->container['encrypt_pdfs_password'] = $encrypt_pdfs_password;

        return $this;
    }

    /**
     * Gets public_submissions
     *
     * @return bool|null
     */
    public function getPublicSubmissions()
    {
        return $this->container['public_submissions'];
    }

    /**
     * Sets public_submissions
     *
     * @param bool|null $public_submissions public_submissions
     *
     * @return $this
     */
    public function setPublicSubmissions($public_submissions)
    {
        $this->container['public_submissions'] = $public_submissions;

        return $this;
    }

    /**
     * Gets shared_field_data
     *
     * @return object|null
     */
    public function getSharedFieldData()
    {
        return $this->container['shared_field_data'];
    }

    /**
     * Sets shared_field_data
     *
     * @param object|null $shared_field_data shared_field_data
     *
     * @return $this
     */
    public function setSharedFieldData($shared_field_data)
    {
        $this->container['shared_field_data'] = $shared_field_data;

        return $this;
    }

    /**
     * Gets document_md5
     *
     * @return string|null
     */
    public function getDocumentMd5()
    {
        return $this->container['document_md5'];
    }

    /**
     * Sets document_md5
     *
     * @param string|null $document_md5 document_md5
     *
     * @return $this
     */
    public function setDocumentMd5($document_md5)
    {
        $this->container['document_md5'] = $document_md5;

        return $this;
    }

    /**
     * Gets first_template
     *
     * @return bool|null
     */
    public function getFirstTemplate()
    {
        return $this->container['first_template'];
    }

    /**
     * Sets first_template
     *
     * @param bool|null $first_template first_template
     *
     * @return $this
     */
    public function setFirstTemplate($first_template)
    {
        $this->container['first_template'] = $first_template;

        return $this;
    }

    /**
     * Gets defaults
     *
     * @return \DocSpring\Model\Template1Defaults|null
     */
    public function getDefaults()
    {
        return $this->container['defaults'];
    }

    /**
     * Sets defaults
     *
     * @param \DocSpring\Model\Template1Defaults|null $defaults defaults
     *
     * @return $this
     */
    public function setDefaults($defaults)
    {
        $this->container['defaults'] = $defaults;

        return $this;
    }

    /**
     * Gets editable_submissions
     *
     * @return bool|null
     */
    public function getEditableSubmissions()
    {
        return $this->container['editable_submissions'];
    }

    /**
     * Sets editable_submissions
     *
     * @param bool|null $editable_submissions editable_submissions
     *
     * @return $this
     */
    public function setEditableSubmissions($editable_submissions)
    {
        $this->container['editable_submissions'] = $editable_submissions;

        return $this;
    }

    /**
     * Gets expire_submissions
     *
     * @return bool|null
     */
    public function getExpireSubmissions()
    {
        return $this->container['expire_submissions'];
    }

    /**
     * Sets expire_submissions
     *
     * @param bool|null $expire_submissions expire_submissions
     *
     * @return $this
     */
    public function setExpireSubmissions($expire_submissions)
    {
        $this->container['expire_submissions'] = $expire_submissions;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets footer_html
     *
     * @return string|null
     */
    public function getFooterHtml()
    {
        return $this->container['footer_html'];
    }

    /**
     * Sets footer_html
     *
     * @param string|null $footer_html footer_html
     *
     * @return $this
     */
    public function setFooterHtml($footer_html)
    {
        $this->container['footer_html'] = $footer_html;

        return $this;
    }

    /**
     * Gets document_parse_error
     *
     * @return bool|null
     */
    public function getDocumentParseError()
    {
        return $this->container['document_parse_error'];
    }

    /**
     * Sets document_parse_error
     *
     * @param bool|null $document_parse_error document_parse_error
     *
     * @return $this
     */
    public function setDocumentParseError($document_parse_error)
    {
        $this->container['document_parse_error'] = $document_parse_error;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return object|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param object|null $fields fields
     *
     * @return $this
     */
    public function setFields($fields)
    {
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets document_filename
     *
     * @return string|null
     */
    public function getDocumentFilename()
    {
        return $this->container['document_filename'];
    }

    /**
     * Sets document_filename
     *
     * @param string|null $document_filename document_filename
     *
     * @return $this
     */
    public function setDocumentFilename($document_filename)
    {
        $this->container['document_filename'] = $document_filename;

        return $this;
    }

    /**
     * Gets redirect_url
     *
     * @return string|null
     */
    public function getRedirectUrl()
    {
        return $this->container['redirect_url'];
    }

    /**
     * Sets redirect_url
     *
     * @param string|null $redirect_url redirect_url
     *
     * @return $this
     */
    public function setRedirectUrl($redirect_url)
    {
        $this->container['redirect_url'] = $redirect_url;

        return $this;
    }

    /**
     * Gets document_url
     *
     * @return string|null
     */
    public function getDocumentUrl()
    {
        return $this->container['document_url'];
    }

    /**
     * Sets document_url
     *
     * @param string|null $document_url document_url
     *
     * @return $this
     */
    public function setDocumentUrl($document_url)
    {
        $this->container['document_url'] = $document_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


