<?php
/**
 * Template1DefaultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocSpring
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DocSpring;

/**
 * Template1DefaultsTest Class Doc Comment
 *
 * @category    Class
 * @description Template1Defaults
 * @package     DocSpring
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Template1DefaultsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Template1Defaults"
     */
    public function testTemplate1Defaults()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "font_size"
     */
    public function testPropertyFontSize()
    {
    }

    /**
     * Test attribute "typeface"
     */
    public function testPropertyTypeface()
    {
    }
}
