<?php
/**
 * Template1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocSpring
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DocSpring;

/**
 * Template1Test Class Doc Comment
 *
 * @category    Class
 * @description Template1
 * @package     DocSpring
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Template1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Template1"
     */
    public function testTemplate1()
    {
    }

    /**
     * Test attribute "document_processed"
     */
    public function testPropertyDocumentProcessed()
    {
    }

    /**
     * Test attribute "expiration_interval"
     */
    public function testPropertyExpirationInterval()
    {
    }

    /**
     * Test attribute "scss"
     */
    public function testPropertyScss()
    {
    }

    /**
     * Test attribute "document_state"
     */
    public function testPropertyDocumentState()
    {
    }

    /**
     * Test attribute "expire_after"
     */
    public function testPropertyExpireAfter()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "slack_webhook_url"
     */
    public function testPropertySlackWebhookUrl()
    {
    }

    /**
     * Test attribute "demo"
     */
    public function testPropertyDemo()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "header_html"
     */
    public function testPropertyHeaderHtml()
    {
    }

    /**
     * Test attribute "public_web_form"
     */
    public function testPropertyPublicWebForm()
    {
    }

    /**
     * Test attribute "field_order"
     */
    public function testPropertyFieldOrder()
    {
    }

    /**
     * Test attribute "permanent_document_url"
     */
    public function testPropertyPermanentDocumentUrl()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "template_type"
     */
    public function testPropertyTemplateType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "page_dimensions"
     */
    public function testPropertyPageDimensions()
    {
    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {
    }

    /**
     * Test attribute "page_count"
     */
    public function testPropertyPageCount()
    {
    }

    /**
     * Test attribute "encrypt_pdfs"
     */
    public function testPropertyEncryptPdfs()
    {
    }

    /**
     * Test attribute "webhook_url"
     */
    public function testPropertyWebhookUrl()
    {
    }

    /**
     * Test attribute "embed_domains"
     */
    public function testPropertyEmbedDomains()
    {
    }

    /**
     * Test attribute "parent_folder_id"
     */
    public function testPropertyParentFolderId()
    {
    }

    /**
     * Test attribute "allow_additional_properties"
     */
    public function testPropertyAllowAdditionalProperties()
    {
    }

    /**
     * Test attribute "encrypt_pdfs_password"
     */
    public function testPropertyEncryptPdfsPassword()
    {
    }

    /**
     * Test attribute "public_submissions"
     */
    public function testPropertyPublicSubmissions()
    {
    }

    /**
     * Test attribute "shared_field_data"
     */
    public function testPropertySharedFieldData()
    {
    }

    /**
     * Test attribute "document_md5"
     */
    public function testPropertyDocumentMd5()
    {
    }

    /**
     * Test attribute "first_template"
     */
    public function testPropertyFirstTemplate()
    {
    }

    /**
     * Test attribute "defaults"
     */
    public function testPropertyDefaults()
    {
    }

    /**
     * Test attribute "editable_submissions"
     */
    public function testPropertyEditableSubmissions()
    {
    }

    /**
     * Test attribute "expire_submissions"
     */
    public function testPropertyExpireSubmissions()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "footer_html"
     */
    public function testPropertyFooterHtml()
    {
    }

    /**
     * Test attribute "document_parse_error"
     */
    public function testPropertyDocumentParseError()
    {
    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {
    }

    /**
     * Test attribute "document_filename"
     */
    public function testPropertyDocumentFilename()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }

    /**
     * Test attribute "document_url"
     */
    public function testPropertyDocumentUrl()
    {
    }
}
